name: harmonymusic
description: A cross platform app for music streaming.
publish_to: "none"
version: 1.12.1+26

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  animations: ^2.0.11
  app_links: ^6.0.0
  archive: ^3.5.0
  audio_service: ^0.18.12
  audio_service_mpris: ^0.2.0
  audio_video_progress_bar: ^2.0.1
  audiotags: ^1.4.2
  buttons_tabbar: ^1.3.8
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_lyric: ^2.0.4+6
  flutter_slidable: ^3.1.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  ionicons: ^0.2.2
  jni: ^0.14.2
  just_audio: ^0.9.36
  just_audio_media_kit:
    git:
      url: https://github.com/anandnet/just_audio_media_kit.git
      ref: 6672eb82657d9e671abbf42122031c88aa9e6d80
  palette_generator: ^0.3.3+3
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  share_plus: ^9.0.0
  shimmer: ^3.0.0
  sidebar_with_animation:
    git:
      url: https://github.com/anandnet/animated_side_bar.git
      branch: main
      ref: b53567a42b4ba3793a3cf00d478bdba0ecce33d7
  smtc_windows: ^0.1.3
  terminate_restart:
    git:
      url: https://github.com/anandnet/terminate_restart.git
      branch: main
      ref: eb505e07e11d0fe1f5c03993e707c6678428c353
  toggle_switch: ^2.3.0
  tray_manager: ^0.5.1
  url_launcher: ^6.2.5
  widget_marquee: ^0.0.8
  window_manager: ^0.5.0
  youtube_explode_dart:
    git:
      url: https://github.com/anandnet/youtube_explode_dart.git
      ref: 1d9ec9baa806705b1d859260eeb389ec28c6b024

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  jnigen: ^0.14.2
  mockito: ^5.4.4
  path_provider_platform_interface: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
